### ISSUE TITLE
Build Issue: `minepy` fails to compile when installed with other dependencies from requirements.txt

### ISSUE THREAD

**Issue by hyrnb** [shioya-lab-public/surgefuzz#1]
I followed your instructions but got this. Can you explain it, please?
![Uploading error.png…]()

**Comment by mmxsrup** [comment]
The error image does not appear to be up. Please check.

**Comment by hyrnb** [comment]
> The error image does not appear to be up. Please check.

<img width="768" alt="error" src="https://github.com/user-attachments/assets/a7c3e8b3-b66d-4546-9904-be8677df9861">

**Comment by mmxsrup** [comment]
I confirmed the same error in my environment. It seems that some library update has caused the error. Please give me some time to fix it.

**Comment by hyrnb** [comment]
> I confirmed the same error in my environment. It seems that some library update has caused the error. Please give me some time to fix it.

Thanks a lot.

**Comment by hyrnb** [comment]
> I confirmed the same error in my environment. It seems that some library update has caused the error. Please give me some time to fix it.

Could you inform me when you fix it, please?

**Comment by mmxsrup** [comment]
Apologies for the delay. I have added a commit to fix it.
